name: books_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1
  json_annotation: ^4.8.1
  
  #State managment
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  #Storage
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2

  #UI
  flutter_screenutil: ^5.9.0
  device_preview: ^1.1.0
  google_fonts: 6.1.0
  linear_progress_bar: ^1.1.1
  cupertino_modal_sheet: ^1.1.0

  #Settings
  url_launcher: ^6.2.4
  in_app_review: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

  #Icons
  flutter_launcher_icons: ^0.13.1
  
flutter_launcher_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon/launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/navbar/
    - assets/icons/app_icon/